### ISSUE TITLE
[SUGGESTION] Restore Infravision with AD&D (inspired) penalties

### ISSUE THREAD

**Issue by Salk73** [BartyMae/IR_Revised#19] opened 2024-11-30 06:13 UTC
Hello, Bartimaeus!

I hope you'll return to us at G3 soon, but in the meantime I will just open an "issue" here to ask for the implementation of something that was [mentioned by Isewein at G3](https://www.gibberlings3.net/forums/topic/38923-suggestion-make-infravision-useful/).

Infravision could be made useful by introducing a THAC0 penalty for those not having it at night time / dungeon areas. It seems like AD&D has a standard -4 THAC0 penalty in those cases. Perhaps a bit steep (you may consider halving it and apply it to all game's creatures).

True Strike could still be added by SRR as new Divination spell. This school is after all in need of all the help modders can give it.

UPDATE: Sorry, I noticed I opened this issue on the IRR page rather than SRR. Please feel free to erase it because it seems I cannot do it myself.

**Comment by BartyMae** [comment] 2024-12-04 06:11
I just don't think this is something SRR can do by itself (i.e. it's something that has to be done in base SR and which I could then match for SRR), for reasons that are kind of complicated but which I'll try to explain:

1. Even if I were inclined to just straight up steal the idea, I feel it's a little outside the scope of SR/R to impose a -4 penalty to THAC0 to what is essentially just humans in the dark - that's an especially big malus at the beginning of BG1 that players may not want (poor Imoen!). That particular tweak is more appropriate to Anthology Tweaks...but it makes for a rather awkward situation where SR/R doesn't know whether or not that penalty is (or at least will be) there or not, especially because Anthology Tweaks is always installed later (sometimes MUCH later) than SR/R.
2. If the penalty is not there, then restoring Infravision doesn't serve much point...if it is there, then what, we need to have both True Strike and Infravision exist? Well, True Strike took over Infravision's old .itm code for its scroll, so you need to create a new scroll .itm and place them in-game, which is always a big pain in the butt to do throughout all BG1, BG2, BGT/EET games. But SR/R wouldn't even be able to determine whether it wants to restore Infravision in the first place at the time of install...
3. Any compatibility made between Anthology Tweaks and SR for this would be coded according to the current state of how SR handles the situation: this means that SRR's behavior must match SR's or risk an unnecessary incompatibility.

It's not a great situation to be in. About all I feel I can realistically do is just go ahead and restore Infravision without knowing whether it serves any purpose or not, just on the off-chance that the player might be playing with that tweak. But it takes time and effort to place scrolls, for a not particularly great likelihood of any benefit, and maybe the multiple Rings of Infravision found throughout BG1, including one on Nimbul and another at the Nashkel Carnival, is enough to cover any issues to make restoring Infravision not really worth the trouble for SR/R.

On a side-note, I posted multiple times in the IRR/SRR threads to answer/resolve some of the latest comments there, but they were repeatedly not approved. Here is the the reply I posted probably three or four times months ago in the SRR thread (but saved to a .txt in advance because I had caught onto the fact that my replies were not going to be approved) - you can post it in the thread while pinging the appropriate people if you like, or not...but I don't think I intend to return to the G3 at this point.

Stratagems errors: The same/similar errors occur with an SR install...

> STRATAGEMS component 6000: C6WULF has ranged but not melee weapon
> STRATAGEMS component 6000: C6WULF2 has ranged but not melee weapon
> STRATAGEMS component 6000: DOPTHI01 has ranged but not melee weapon
> STRATAGEMS component 6000: HABIB has ranged but not melee weapon
> STRATAGEMS component 6000: HABIB2 has ranged but not melee weapon
> STRATAGEMS component 6000: JAGA1 has ranged but not melee weapon
> STRATAGEMS component 6000: JELLGR has ranged but not melee weapon
> STRATAGEMS component 6000: KINDAI has ranged but not melee weapon
> STRATAGEMS component 6000: LISSA has ranged but not melee weapon
> STRATAGEMS component 6000: MAJAN has ranged but not melee weapon
> STRATAGEMS component 6000: MGAPPR01 has ranged but not melee weapon
> STRATAGEMS component 6000: MGAPPR02 has ranged but not melee weapon
> STRATAGEMS component 6000: MGAPPR03 has ranged but not melee weapon
> STRATAGEMS component 6000: OHHSPID1 has ranged but not melee weapon
> STRATAGEMS component 6000: Failed to insert script dw#gphlp above gpmerc in file OHRSGUA1
> STRATAGEMS component 6000: QUAYLE has ranged but not melee weapon
> STRATAGEMS component 6000: SCHLUM has ranged but not melee weapon
> STRATAGEMS component 6000: SLIFIS01 has ranged but not melee weapon
> STRATAGEMS component 6000: SLIFIS02 has ranged but not melee weapon
> STRATAGEMS component 6000: THRAXI has ranged but not melee weapon
> STRATAGEMS component 6000: VAELAG has ranged but not melee weapon
> STRATAGEMS component 6000: WULFGAR has ranged but not melee weapon
> STRATAGEMS component 6030: No recorded level for spell WIZARD_NULL
> STRATAGEMS component 6030: SCS's 'mage_edits_main' function has encountered a file it doesn't know how to patch, CLONE1.CRE (probably the file was broken by a previous mod). The error message was 'Not_found'. SCS has skipped it and continued with installation, but this may cause instabilities.
> STRATAGEMS component 6030: SCS's 'mage_edits_main' function has encountered a file it doesn't know how to patch, KALAH.CRE (probably the file was broken by a previous mod). The error message was 'Not_found'. SCS has skipped it and continued with installation, but this may cause instabilities.
> STRATAGEMS component 6030: SCS's 'mage_edits_main' function has encountered a file it doesn't know how to patch, MAGE8E.CRE (probably the file was broken by a previous mod). The error message was 'Not_found'. SCS has skipped it and continued with installation, but this may cause instabilities.
> STRATAGEMS component 6030: SCS's 'mage_edits_main' function has encountered a file it doesn't know how to patch, OHNMIRON.CRE (probably the file was broken by a previous mod). The error message was 'Not_found'. SCS has skipped it and continued with installation, but this may cause instabilities.
> STRATAGEMS component 6030: SCS's 'mage_edits_main' function has encountered a file it doesn't know how to patch, OHNZAVIA.CRE (probably the file was broken by a previous mod). The error message was 'Not_found'. SCS has skipped it and continued with installation, but this may cause instabilities.
> STRATAGEMS component 6030: SCS's 'mage_edits_main' function has encountered a file it doesn't know how to patch, REBAND04.CRE (probably the file was broken by a previous mod). The error message was 'Not_found'. SCS has skipped it and continued with installation, but this may cause instabilities.
> STRATAGEMS component 6030: SCS's 'mage_edits_main' function has encountered a file it doesn't know how to patch, SUELFW9.CRE (probably the file was broken by a previous mod). The error message was 'Not_found'. SCS has skipped it and continued with installation, but this may cause instabilities.
> STRATAGEMS component 6030: SCS's 'mage_edits_main' function has encountered a file it doesn't know how to patch, XAPPREN1.CRE (probably the file was broken by a previous mod). The error message was 'Not_found'. SCS has skipped it and continued with installation, but this may cause instabilities.
> STRATAGEMS component 6030: SCS's 'mage_edits_main' function has encountered a file it doesn't know how to patch, XAPPREN2.CRE (probably the file was broken by a previous mod). The error message was 'Not_found'. SCS has skipped it and continued with installation, but this may cause instabilities.

...so it's not an SRR-specific issue. I don't really know what the issue is, especially insofar as these errors affect creatures not directly modified by SR/R in the first place - indirectly, SR/R might've changed some of the spells used by the affected spellcasters, but most of the warnings for Stratagems component 6000 don't even pertain to spellcasters. I would guess those errors are harmless, but I don't know for certain...and as for the second group of errors with component 6030, the end result seems to be that those handful of mages weren't modified by Smarter Mages. Which sounds relatively harmless for that particular group of spellcasters, but again, I don't really know for sure: diagnosing Stratagems install errors/warnings is a bit outside my wheelhouse. The error listed in the .DEBUG file seems to suggest that SCS is having trouble finding or parsing some particular spell...

> [./override/CLONE1.CRE] loaded, 1368 bytes
> 
> Determining spells and script for CLONE1
> 
> SFO warning: No recorded level for spell WIZARD_NULL
> [weidu_external/data/STRATAGEMS/sfo_warnings.txt] loaded, 1512 bytes
> Appending to files ...
> [weidu_external/data/STRATAGEMS/sfo_warnings.txt] loaded, 1512 bytes
> weidu_external/data/STRATAGEMS/sfo_warnings.txt copied to weidu_external/backup/stratagems/6030/sfo_warnings.txt, 1512 bytes
> Appended text to [weidu_external/data/STRATAGEMS/sfo_warnings.txt]
> ERROR: cannot convert %WIZARD_NULL_LEVEL% or %%WIZARD_NULL_LEVEL%% to an integer
> 
> SCS's 'mage_edits_main' function has encountered a file it doesn't know how to patch, CLONE1.CRE (probably the file was broken by a previous mod). The error message was 'Not_found'. SCS has skipped it and continued with installation, but this may cause instabilities.
> 
> SFO warning: SCS's 'mage_edits_main' function has encountered a file it doesn't know how to patch, CLONE1.CRE (probably the file was broken by a previous mod). The error message was 'Not_found'. SCS has skipped it and continued with installation, but this may cause instabilities.
> [weidu_external/data/STRATAGEMS/sfo_warnings.txt] loaded, 1580 bytes
> Appending to files ...
> [weidu_external/data/STRATAGEMS/sfo_warnings.txt] loaded, 1580 bytes
> Appended text to [weidu_external/data/STRATAGEMS/sfo_warnings.txt]
> override/CLONE1.CRE copied to weidu_external/backup/stratagems/6030/CLONE1.CRE, 1368 bytes

...but "WIZARD_NULL", while probably intending to be a real identifier entry from spell.ids (e.g. WIZARD_MAGIC_MISSILE), doesn't refer to anything. Presumably, it's a spell added by SR/R. I personally wouldn't sweat it that much, it's a pretty small group of spellcasters affected.

. . .

IWDifcation: Sorry, I don't really have any applicable knowledge for IWDification, but what I can say for the spells added by SCS's is that for if SR/R is installed before SCS is, then SCS should skip adding or overwriting those spells again, thereby keeping SR/R's versions. I don't know if it works the same way in reverse (i.e. if you specifically go out of your way to install just the IWD spells from SCS, and then install SR/R afterwards, I don't know if SR/R is smart enough to not try to still install its duplicate spells). In general, SR/R is supposed to always be installed before SCS is, but if one wanted the SCS versions of those spells, you could install just those specific SCS components before SR/R and see how that works out.

. . .

Chill Touch: The original SR Chill Touch doesn't have the scaling damage, it always just does the 1D6 cold damage...so at least that part of SRR's SPWI117D.spl is working correctly, haha. Most likely, I revised it to be -2 because...well, a -1 penalty won't likely do anything at all regardless of whether you're using 2E non-linear or 3E linear stats, so the logic was to increase it...but then on second thought, if you're using the game's default 2E stats, that still might not have any kind of discernable effect, so it's generally better to not bother with ability score penalties when you don't have to and instead just directly penalize the stats you want to be affected (in this case, THAC0 and damage). After all, this is supposed to compete with Shocking Grasp, and Shocking Grasp will stun an enemy for a round, which can actually be a pretty devastating effect even for just one round when you're at low level. 5 turns was the original length of the strength penalty in SR, 5 rounds is the intended length for the revised THAC0/damage penalty. Regardless, thanks, I fixed it to be how I intended but apparently did not implement it (and also, I'm increasing the penalty to a turn instead of 5 rounds).

**Comment by Salk73** [comment] 2024-12-04 07:10
Hello, mate!

Thanks for the detailed answer here on GitHub. I'm truly sorry that you've to go through such annoyance at G3 and I must admit I am not understanding. Why wouldn't G3 approve your posts...? Or can you even log in using your credentials anymore? Have I missed something?

I'd really like to have a chance to communicate with you directly again without spamming your GitHub space, but I don't want to impose so I will just leave my email here to you in case you are okay with it: crimes73@gmail.com. I check it daily so please, don't hesitate sending a short note, if you so please.

About the Infravision restoration, I must say I do understand where you're coming from. It's true that it is a spell that would just penalize the human race. In fact, someone suggested that this penalty should be "compensated" by making human NPCs gain some small extra bonus. That does sound too convoluted, so perhaps it's just as well that Infravision is gone for good.

Cheers!

**Comment by BartyMae** [comment] 2024-12-06 04:56
I deleted my G3 credentials from my password manager and committed to only guest posting after realizing it's the superior avenue for posting. No-one can put you on their ignore list, you can post whatever you like so long so long as it's _directly_ approved of by staff, you can't be told to take a discussion to PMs because you're not a member and thus cannot send nor receive PMs, you can double-post instead of editing because guests can't edit previous posts even if they want to, nobody can search through your post history, and best of all, you can't be harassed with pings/quotes from other members **or guests**. My mistake was that I didn't foresee not being allowed to post as a guest, despite my posts being perfectly on topic and containing neither misleading or inflammatory content (not that any of that has historically meant very much for approving guest posts on the G3). But if my posts are not welcome at the G3, and they don't seem to be, then c'est la vie, I can live without it. I'll check back every once in a while for further posts and if I need to make any fixes, but as I said, I do not intend to return to the G3 at this point.

Feel free to open up any number of issues here on GitHub for whatever you like - I get email notifications for both opened issues and any replies to them.

**Closed as completed** 2024-12-15 05:51 UTC
